name: project_vision
description: Project Vision is an open-source cross-platform mobile application project that incorporates Machine Learning to help visually impaired people recognize different currency bills and perform daily cash transactions more effectively.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.8.1+7
  tflite: ^1.1.2
  sqflite: ^2.0.1
  path_provider: ^2.0.4
  cupertino_icons: ^1.0.4
  flutter_vibrate: ^1.3.0
  intl: ^0.17.0
  light: ^2.1.0
  flutter_tts: 3.0.0
  connectivity:

dev_dependencies:
  google_fonts: ^2.1.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/cash_recognition/models/uae_model/
    - assets/cash_recognition/images/
    - assets/object_recognition/images/
    - assets/object_recognition/models/
    - assets/